### ISSUE TITLE
Problems finding resources

### ISSUE THREAD

**Issue by NickCody** [groovydev/twitter-bootstrap-grails-plugin#125]
A basic project I created is having trouble locating resources. I get this on startup:

```
| Error 2014-12-02 10:01:54,280 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /plugins/twitter-bootstrap-2.3.2.2/css/bootstrap-fixtaglib.css
```

And this when I load a page:

```
Caused by IllegalArgumentException: Module [bootstrap-transition] depends on resource [/plugins/twitter-bootstrap-2.3.2.2/js/bootstrap-transition.js] but the file cannot be found
```

(the exact resource is somewhat random)

I am upgrading to Grails 2.4.4 using the resources plugin. I am trying resources plugin because my app uses it and it would take a lot of effort to move to asset pipeline. I am also using the 2.3.2.2 patched grails twitter-bootstrap plugin for Bootstrap 2.3. This happens if I include lesscss-resources or leave it out.

The basic project can be looked at here:https://github.com/NickCody/grails-basic

I hope this is enough information to demonstrate my problem.

Thanks in advance for any insight.

**Comment by parthbhagat** [comment]
> You can probably close this issue. I had grails.resources.resourceLocatorEnabled set to true. Setting it to false eliminated the error.

This works for me with my Grails application. Thank you.
